### ISSUE TITLE
Heckle Crashes on Rails 2.3.6 controller

### ISSUE THREAD

**Issue by rurounijones** [ryansobol/heckle#1]
Created a Rails scaffold and added some CanCan authorization and rspec tests.

spec spec -H User results in the following (Sorry, cannot show the base code)

```
UsersController#create loaded with 19 possible mutations                                                                                                                       
**********************************************************************   


19 mutations remaining...
/usr/lib/ruby/gems/1.8/gems/heckle-1.4.3/lib/heckle.rb:603:in `current_code':     undefined method `translate' for Ruby2Ruby:Class (NoMethodError)
    from /usr/lib/ruby/gems/1.8/gems/heckle-1.4.3/lib/heckle.rb:202:in `record_passing_mutation'
    from /usr/lib/ruby/gems/1.8/gems/heckle-1.4.3/lib/heckle.rb:149:in `run_tests'
    from /usr/lib/ruby/gems/1.8/gems/heckle-1.4.3/lib/heckle.rb:173:in `validate'
    from /usr/lib/ruby/1.8/timeout.rb:62:in `timeout'
    from /usr/lib/ruby/1.8/timeout.rb:93:in `timeout'
    from /usr/lib/ruby/gems/1.8/gems/heckle-1.4.3/lib/heckle.rb:173:in `validate'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/heckle_runner.rb:44:in `heckle_class_or_module'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/heckle_runner.rb:42:in `each'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/heckle_runner.rb:42:in `heckle_class_or_module'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/heckle_runner.rb:41:in `each'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/heckle_runner.rb:41:in `heckle_class_or_module'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/heckle_runner.rb:23:in `heckle_with'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/options.rb:364:in `heckle'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/options.rb:154:in `run_examples'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/lib/spec/runner/command_line.rb:9:in `run'
    from /usr/lib/ruby/gems/1.8/gems/rspec-1.3.0/bin/spec:5
    from /usr/bin/spec:19:in `load'
    from /usr/bin/spec:19
```

**Comment by ryansobol** [comment]
This isn't the official heckle repository and I'm no longer maintaining this code.  I suggest you check out http://github.com/seattlerb/heckle
