### ISSUE TITLE
Block that always causes a syntax error

### ISSUE THREAD

**Issue by mockdeep** [ryansobol/heckle#3]
I've come across a block of code I can't heckle because it always causes a syntax error.  Style issues aside, here's the block:

``` ruby
 def my_awesome_method
   begin
     if true
       puts "cool"
     end
     {}.delete(:whatever)
   rescue 
     puts "weird"
   end
 end
```

Heckle tries to replace the block as such:

``` ruby
--- original
+++ mutation
 def my_awesome_method
   begin
     (puts("cool") if true
-    {  }.delete(:whatever)) rescue puts("weird")
+    # do nothing) rescue puts("weird")
   end
 end
```

Not sure if this is an issue directly with heckle or one of the libraries it uses, e.g. ParseTree.

**Comment by mockdeep** [comment]
Here's the stack trace:

```
/home/fletch/.rvm/gems/ruby-1.8.7-p352@work/gems/heckle-1.4.3/bin/../lib/heckle.rb:505:in `current_tree': sexp invalid for MyCoolClass#my_awesome_method (RuntimeError)
    from /home/fletch/.rvm/gems/ruby-1.8.7-p352@work/gems/heckle-1.4.3/bin/../lib/heckle.rb:518:in `reset_tree'
    from /home/fletch/.rvm/gems/ruby-1.8.7-p352@work/gems/heckle-1.4.3/bin/../lib/heckle.rb:170:in `validate'
    from /home/fletch/.rvm/gems/ruby-1.8.7-p352@work/gems/heckle-1.4.3/bin/../lib/test_unit_heckler.rb:80:in `validate'
    from /home/fletch/.rvm/gems/ruby-1.8.7-p352@work/gems/heckle-1.4.3/bin/../lib/test_unit_heckler.rb:79:in `each'
    from /home/fletch/.rvm/gems/ruby-1.8.7-p352@work/gems/heckle-1.4.3/bin/../lib/test_unit_heckler.rb:79:in `validate'
    from /home/fletch/.rvm/gems/ruby-1.8.7-p352@work/gems/heckle-1.4.3/bin/heckle:95
    from /home/fletch/.rvm/gems/ruby-1.8.7-p352@work/bin/heckle:19:in `load'
    from /home/fletch/.rvm/gems/ruby-1.8.7-p352@work/bin/heckle:19
```
