### ISSUE TITLE
Doesn't work with Ruby 2.3.1

### ISSUE THREAD

**Issue by jaysonvirissimo** [ryansobol/heckle#4]
```
Jaysons-Air:dotcom jaysonvirissimo$ heckle -f Order
/Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ParseTree-3.0.8/lib/parse_tree.rb:3:in `<top (required)>': ParseTree doesn't work with ruby 2.3.1 (LoadError)
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/heckle-1.4.3/lib/heckle.rb:2:in `<top (required)>'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/heckle-1.4.3/lib/test_unit_heckler.rb:5:in `<top (required)>'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/heckle-1.4.3/bin/heckle:4:in `<top (required)>'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/bin/heckle:23:in `load'
    from /Users/jaysonvirissimo/.rbenv/versions/2.3.1/bin/heckle:23:in `<main>'

```

**Comment by jaysonvirissimo** [comment]
Looks like [ParseTree](https://github.com/seattlerb/parsetree) has reached EOL, but [ruby_parser](https://github.com/seattlerb/ruby_parser) has the same output, so should work for this purpose.

**Comment by bothaus** [comment]
Any update to this? Heckle is not working for me
